@echo off
rem ================================================================
rem  RP_COMPILER :: модуль BUILD -- сборка готового main.cpp.
rem
rem  Порядок склейки (см. также builder\README.md):
rem    src\00_header.inc       заголовки, константы, типы
rem    tmp\gen_support.inc     SUPPORT  (генерируется из data\support.txt)
rem    src\20_macros.inc       макросы CMD (статический фрагмент)
rem    tmp\gen_auth.inc        AUTH     (генерируется из data\auth.txt)
rem    src\40_keyboard.inc     данные клавиатуры (статический фрагмент)
rem    tmp\gen_groups.inc      список групп (генерируется)
rem    src\50_engine.inc       энкодер/HID/OLED/действия
rem    src\60_keyboard_ui.inc  интерфейс клавиатуры
rem    src\70_main.inc         USB-дескрипторы и main()
rem  Результат: out\main.cpp
rem ================================================================
setlocal EnableExtensions DisableDelayedExpansion
cd /d "%~dp0.."
if not exist out mkdir out
if not exist tmp mkdir tmp

echo ==================================================
echo           BUILD :: сборка main.cpp
echo ==================================================
echo.

rem ---------- 1. проверка наличия фрагментов и конфигов ----------
set "B_FAIL="
for %%F in ("src\00_header.inc" "src\20_macros.inc" "src\40_keyboard.inc" "src\50_engine.inc" "src\60_keyboard_ui.inc" "src\70_main.inc") do if not exist %%F (
  echo   [!] Не найден фрагмент: %%~F
  if /i "%%~nxF"=="20_macros.inc" echo       Скопируйте src\20_macros.inc.example в src\20_macros.inc
  set "B_FAIL=1"
)
if not exist "data\support.txt" (
  echo   [!] Нет data\support.txt. Добавьте хотя бы одну фразу
  echo       через меню 2 или скопируйте data\support.txt.example.
  set "B_FAIL=1"
)
if not exist "data\auth.txt" (
  echo   [!] Нет data\auth.txt. Добавьте хотя бы один пароль
  echo       через меню 1 или скопируйте data\auth.txt.example.
  set "B_FAIL=1"
)
if defined B_FAIL (
  echo.
  echo   Сборка прервана.
  pause
  exit /b 1
)

rem ---------- 2. секция SUPPORT ----------
if exist tmp\gen_support.inc del tmp\gen_support.inc
set "SUP_COUNT=0"
>>tmp\gen_support.inc echo // ============================================================
>>tmp\gen_support.inc echo //  SUPPORT -- GENERATED by the builder from data\support.txt.
>>tmp\gen_support.inc echo //  Do not edit manually: change phrases via the builder
>>tmp\gen_support.inc echo //  ^(main menu, item 2^) and rebuild the project.
>>tmp\gen_support.inc echo // ============================================================
>>tmp\gen_support.inc echo.
>>tmp\gen_support.inc echo // ================= SUPPORT =================
for /f "tokens=1* delims=:" %%A in ('findstr /n "^" data\support.txt') do call :b_support_arr "%%B"
if "%SUP_COUNT%"=="0" goto :b_err_support
>>tmp\gen_support.inc echo static const Item support_items[] = {
for /f "tokens=1* delims=:" %%A in ('findstr /n "^" data\support.txt') do call :b_support_item "%%B"
>>tmp\gen_support.inc echo };
>>tmp\gen_support.inc echo.

rem ---------- 3. секция AUTH ----------
if exist tmp\gen_auth.inc del tmp\gen_auth.inc
set "AUTH_COUNT=0"
>>tmp\gen_auth.inc echo // ============================================================
>>tmp\gen_auth.inc echo //  AUTH -- GENERATED by the builder from data\auth.txt.
>>tmp\gen_auth.inc echo //  Do not edit manually: change passwords via the builder
>>tmp\gen_auth.inc echo //  ^(main menu, item 1^) and rebuild the project.
>>tmp\gen_auth.inc echo // ============================================================
>>tmp\gen_auth.inc echo.
>>tmp\gen_auth.inc echo // ================= AUTH =================
for /f "tokens=1* delims=:" %%A in ('findstr /n "^" data\auth.txt') do call :b_auth_arr "%%B"
if "%AUTH_COUNT%"=="0" goto :b_err_auth
>>tmp\gen_auth.inc echo static const Item auth_items[] = {
for /f "tokens=1* delims=:" %%A in ('findstr /n "^" data\auth.txt') do call :b_auth_item "%%B"
>>tmp\gen_auth.inc echo };
>>tmp\gen_auth.inc echo.

rem ---------- 4. список групп ----------
if exist tmp\gen_groups.inc del tmp\gen_groups.inc
>>tmp\gen_groups.inc echo // ============================================================
>>tmp\gen_groups.inc echo //  Group list -- GENERATED by the builder.
>>tmp\gen_groups.inc echo //  Item counts are computed automatically via sizeof.
>>tmp\gen_groups.inc echo // ============================================================
>>tmp\gen_groups.inc echo.
>>tmp\gen_groups.inc echo static const Group groups[] = {
>>tmp\gen_groups.inc echo(    {"CMD", cmd_items, (int)(sizeof(cmd_items) / sizeof(cmd_items[0]))},
>>tmp\gen_groups.inc echo(    {"SUPPORT", support_items, (int)(sizeof(support_items) / sizeof(support_items[0]))},
>>tmp\gen_groups.inc echo(    {"AUTH", auth_items, (int)(sizeof(auth_items) / sizeof(auth_items[0]))},
>>tmp\gen_groups.inc echo(    keyboard_group
>>tmp\gen_groups.inc echo };
>>tmp\gen_groups.inc echo.
>>tmp\gen_groups.inc echo static const int group_count = 4;
>>tmp\gen_groups.inc echo.

rem ---------- 5. склейка ----------
if exist out\main.cpp del out\main.cpp
copy /b src\00_header.inc+tmp\gen_support.inc+src\20_macros.inc+tmp\gen_auth.inc+src\40_keyboard.inc+tmp\gen_groups.inc+src\50_engine.inc+src\60_keyboard_ui.inc+src\70_main.inc out\main.cpp >nul
if errorlevel 1 (
  echo   [!] Ошибка склейки файлов.
  pause
  exit /b 1
)

echo.
echo   [OK] Файл собран: out\main.cpp
echo.
echo        SUPPORT, пунктов: %SUP_COUNT%
echo        AUTH, пунктов:    %AUTH_COUNT%
echo        CMD-макросы:      src\20_macros.inc
echo        Клавиатура:       src\40_keyboard.inc
echo.
echo   Дальше: скопируйте out\main.cpp в ваш проект RP2040
echo   и соберите его Pico SDK как обычно (нужны заголовки
echo   ssd1306_i2c.h и ru_keys.h из вашего проекта).
echo.
pause
exit /b 0

rem ==================== ПОДПРОГРАММЫ ====================

:b_err_support
echo.
echo   [!] В data\support.txt нет ни одной корректной фразы.
echo       Добавьте фразу через меню 2 и повторите сборку.
pause
exit /b 1

:b_err_auth
echo.
echo   [!] В data\auth.txt нет ни одного корректного пароля.
echo       Добавьте пароль через меню 1 и повторите сборку.
pause
exit /b 1

rem --- разбор строки конфига. Вход: SL. Выход: S_NAME/S_TOKENS/S_PHRASE
:b_parse_line
set "S_NAME="
set "S_TOKENS="
set "S_PHRASE="
set "S_REST="
for /f "tokens=1* delims=|" %%X in ("%SL%") do set "S_NAME=%%X" & set "S_REST=%%Y"
for /f "tokens=1* delims=|" %%X in ("%S_REST%") do set "S_TOKENS=%%X" & set "S_PHRASE=%%Y"
exit /b

rem --- массив одной фразы SUPPORT
:b_support_arr
set "SL=%~1"
if not defined SL exit /b
setlocal EnableDelayedExpansion
if "!SL:~0,1!"==";" endlocal & exit /b
endlocal
call :b_parse_line
if not defined S_NAME exit /b
if not defined S_TOKENS (
  echo   [!] Пропущена строка без токенов: "%SL%"
  exit /b
)
set "S_ARR=%S_NAME: =_%"
>>tmp\gen_support.inc echo static const uint8_t sup_%S_ARR%[] = {
call :b_write_tokens "%S_TOKENS%" tmp\gen_support.inc
>>tmp\gen_support.inc echo };
>>tmp\gen_support.inc echo.
set /a SUP_COUNT+=1
exit /b

rem --- пункт support_items[]
:b_support_item
set "SL=%~1"
if not defined SL exit /b
setlocal EnableDelayedExpansion
if "!SL:~0,1!"==";" endlocal & exit /b
endlocal
call :b_parse_line
if not defined S_NAME exit /b
if not defined S_TOKENS exit /b
set "S_ARR=%S_NAME: =_%"
>>tmp\gen_support.inc echo(    {"%S_NAME%", A_TEXT, SIMPLE, sup_%S_ARR%, sizeof(sup_%S_ARR%)},
exit /b

rem --- массив одного пароля AUTH
:b_auth_arr
set "SL=%~1"
if not defined SL exit /b
setlocal EnableDelayedExpansion
if "!SL:~0,1!"==";" endlocal & exit /b
endlocal
call :b_parse_line
if not defined S_NAME exit /b
if not defined S_TOKENS (
  echo   [!] Пропущена строка без токенов: "%SL%"
  exit /b
)
set "S_ARR=%S_NAME: =_%"
>>tmp\gen_auth.inc echo static const uint8_t auth_%S_ARR%[] = {
call :b_write_tokens "%S_TOKENS%" tmp\gen_auth.inc
>>tmp\gen_auth.inc echo };
>>tmp\gen_auth.inc echo.
set /a AUTH_COUNT+=1
exit /b

rem --- пункт auth_items[]
:b_auth_item
set "SL=%~1"
if not defined SL exit /b
setlocal EnableDelayedExpansion
if "!SL:~0,1!"==";" endlocal & exit /b
endlocal
call :b_parse_line
if not defined S_NAME exit /b
if not defined S_TOKENS exit /b
set "S_ARR=%S_NAME: =_%"
>>tmp\gen_auth.inc echo(    {"%S_NAME%", A_SEND, SIMPLE, auth_%S_ARR%, sizeof(auth_%S_ARR%)},
exit /b

rem --- вывод токенов с переносом по 12 штук в строке.
rem     %1 = строка токенов через запятую, %2 = файл
:b_write_tokens
set "WT_REST=%~1"
set "WT_FILE=%~2"
set "WT_LINE=    "
set "WT_N=0"
set "WT_FIRST=1"
:wt_loop
if not defined WT_REST goto :wt_end
for /f "tokens=1* delims=," %%A in ("%WT_REST%") do set "WT_TOK=%%A" & set "WT_REST=%%B"
if "%WT_FIRST%"=="1" (
  set "WT_LINE=    %WT_TOK%"
  set "WT_FIRST=0"
) else (
  set "WT_LINE=%WT_LINE%,%WT_TOK%"
)
set /a WT_N+=1
if "%WT_N%"=="12" (
  >>"%WT_FILE%" echo(%WT_LINE%
  set "WT_LINE=    "
  set "WT_N=0"
)
goto :wt_loop
:wt_end
if not "%WT_N%"=="0" >>"%WT_FILE%" echo(%WT_LINE%
exit /b
