if (NOT DEFINED PICO_SDK_INCLUDED)
    set(PICO_SDK_INCLUDED TRUE)
    if (NOT PICO_SDK_PATH)
        set(PICO_SDK_PATH "${CMAKE_CURRENT_LIST_DIR}/pico-sdk")
    endif ()
    set(PICO_SDK_PATH "${PICO_SDK_PATH}" CACHE PATH "Path to the Pico SDK" FORCE)
    if (NOT EXISTS "${PICO_SDK_PATH}/pico_sdk_init.cmake")
        message(FATAL_ERROR "Pico SDK not found in '${PICO_SDK_PATH}'")
    endif ()
    include("${PICO_SDK_PATH}/pico_sdk_init.cmake")
endif ()
